name: 'cargo-generate'
description: 'Run cargo-generate'
inputs:
  name:
    description: 'Name of the template expansion'
    required: true
  template:
    description: this is passed to the `--path` argument
    required: false
    default: '.'
  arguments:
    description: "The arguments to pass to cargo-generate"
    required: false
    default: '--verbose'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --path
    - ${{ inputs.template }}
    - --name
    - ${{ inputs.name }}
    - ${{ inputs.arguments }}
